# Задание к уроку 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [2]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(200, 50))
A

array([[35, 78, 54, ...,  9, 24, 49],
       [63, 57, 99, ..., 88, 11, 29],
       [81, 39, 57, ..., 29, 53, 41],
       ...,
       [77, 93, 91, ..., 52, 61, 56],
       [82, 95, 89, ..., 10, 43, 40],
       [33, 40, 54, ..., 59, 10,  3]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [3]:
B = A[:, np.random.permutation(A.shape[1])]
B

array([[24,  6, 54, ..., 26, 55, 57],
       [11, 97, 37, ...,  9, 10, 72],
       [53, 57, 39, ..., 33, 83, 69],
       ...,
       [61, 94,  8, ..., 90, 10, 97],
       [43, 18, 62, ..., 38, 92, 58],
       [10,  5, 45, ..., 13, 28,  9]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [4]:
A = np.random.randint(0, 100, size=(200, 50))
r1 = np.ptp(A, 1)
r2 = np.amax(A, 1) - np.amin(A, 1)
assert np.allclose(r1, r2)
print("\nРазница между максимальным и минимальным элементов массива:")
print(r1)
m = max(r1)
[i for i, j in enumerate(r1) if j == m]


Разница между максимальным и минимальным элементов массива:
[88 97 96 98 91 99 96 95 98 95 98 96 99 95 92 98 95 95 96 99 98 96 98 98
 93 97 96 96 98 99 97 97 96 98 95 99 93 97 94 98 96 95 94 93 95 96 96 98
 96 97 97 96 96 96 97 95 96 99 94 97 94 95 93 99 95 97 98 92 97 99 95 98
 96 98 98 98 98 87 86 93 99 94 97 91 99 90 97 99 93 94 93 99 95 94 98 96
 96 98 95 99 92 96 97 93 93 95 94 97 96 98 98 92 95 95 97 96 99 91 97 98
 94 96 96 96 92 95 98 97 97 99 99 99 90 99 93 98 99 96 97 99 88 96 95 93
 94 95 98 97 96 96 98 98 97 99 96 98 95 96 92 94 98 99 98 93 99 98 99 99
 92 95 94 93 94 98 95 97 94 96 97 96 99 97 94 98 95 99 95 97 98 97 98 95
 98 99 94 99 96 94 93 91]


[5,
 12,
 19,
 29,
 35,
 57,
 63,
 69,
 80,
 84,
 87,
 91,
 99,
 116,
 129,
 130,
 131,
 133,
 136,
 139,
 153,
 161,
 164,
 166,
 167,
 180,
 185,
 193,
 195]

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [5]:
A = np.random.randint(0, 100, size=(200, 50))
maxi = A.max()
mini = A.min()
a_norm = (A - mini) / (maxi -mini)
a_norm

array([[0.29292929, 0.44444444, 0.92929293, ..., 0.05050505, 0.02020202,
        0.18181818],
       [0.34343434, 0.55555556, 0.74747475, ..., 0.94949495, 0.41414141,
        0.88888889],
       [0.83838384, 0.61616162, 0.06060606, ..., 0.85858586, 0.98989899,
        0.62626263],
       ...,
       [0.86868687, 0.86868687, 0.72727273, ..., 0.06060606, 0.58585859,
        0.32323232],
       [0.18181818, 0.25252525, 0.09090909, ..., 0.21212121, 0.98989899,
        0.67676768],
       [0.45454545, 0.67676768, 0.95959596, ..., 0.05050505, 0.56565657,
        0.14141414]])

# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [7]:
import pandas as pd
A = pd.DataFrame(np.random.randint(0, 100, size=(200, 50)))
even = A[A.columns[::2]]
odd = A[A.columns[1::2]]
F = pd.concat([even, odd], axis=1)
F


0   2   4   6   8   10  12  14  16  18  ...  31  33  35  37  39  41  43   
0    60  72  46  76  69  10  18  65  97  67  ...  59  78  14  79  57  80  52  \
1    28  48  97  20  63  19  33  27  65  99  ...  97  44  51  49  99  58  53   
2    20  88  86  88  13   1  90  58  66  43  ...  91  13  38  45  63  32  27   
3    36  17  93  26  28  89  58  74  53  89  ...  86  90  22   8  76  16  32   
4    37   2  10  45  72  34  32  96  80  38  ...  96  93   7  50  79  65  16   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
195  95  85  32  20  61   3  23  81  72  50  ...  89  67  75  25  29  93  46   
196  13  66  91  21  76  23  36  90  80  17  ...  31  54  16  29  83  30  19   
197  32  27  73  82  56  12  97  33  26  48  ...  17  22  66  31  39  69   7   
198  54  92  18  58   3  59  50  33  91  70  ...  17  27  20  32  39  56   9   
199  22  31  31  55  18  82   8  35   5  21  ...  54  57  21  34  36  14  67   

     45  47  49  
0     6  59  46  
1    52  49  76  
2    26  13  21  
3     2  37  13  
4    55  29  48  
..   ..  ..  ..  
195  52  60  27  
196  86  92  46  
197  74  80   8  
198  94  70  69  
199  19   7  91  

[200 rows x 50 columns]

# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A` (средний т.е арифметическое среднее)

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике.

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [2]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

[0, 4, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [3]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

2003

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 